const plantsData = [
  {
    id: 1,
    name: "Sansevieria",
    type: ["toxic"],
    img: "img/plant-sansevieria.png",
    light: ["lowlight"],
    watering: "underwater",
  },
  {
    id: 2,
    name: "Peace Lily",
    type: ["toxic", "nonToxic"],
    img: "img/plant-peace-lily.png",
    light: ["lowlight", "mediumlight"],
    watering: "overwater",
  },
  {
    id: 3,
    name: "Boston Fern",
    type: ["nonToxic"],
    img: "img/plant-boston-fern.png",
    light: ["lowlight"],
    watering: "underwater",
  },
  {
    id: 4,
    name: "Aglaonema",
    type: ["toxic"],
    img: "img/plant-aglaonema.png",
    light: ["mediumlight"],
    watering: "underwater",
  },
  {
    id: 5,
    name: "Monstera",
    type: ["nonToxic"],
    img: "img/plant-monstera.png",
    light: ["mediumlight"],
    watering: "underwater",
  },
  {
    id: 6,
    name: "Aloe Vera",
    type: ["toxic"],
    img: "img/plant-aloe.png",
    light: ["outdoor"],
    watering: "underwater",
  },
  {
    id: 7,
    name: "Cactus",
    type: ["nonToxic"],
    img: "./img/plant-cactus.png",
    light: ["outdoor"],
    watering: "underwater",
  },
];

export default plantsData;
